#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Jul 06 22:46:11 CST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto fd470f3287c9458d94242a82ee99f1ad --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot WHUCPU_soc_behav xil_defaultlib.WHUCPU_soc xil_defaultlib.glbl -log elaborate.log"
xelab -wto fd470f3287c9458d94242a82ee99f1ad --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot WHUCPU_soc_behav xil_defaultlib.WHUCPU_soc xil_defaultlib.glbl -log elaborate.log

