# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/225/2020MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/i/sign_div/sign_div.xci
# IP: The module: 'sign_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/225/2020MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/i/sign_div/sign_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sign_div'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/225/2020MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/i/sign_div/sign_div.xci
# IP: The module: 'sign_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/225/2020MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/i/sign_div/sign_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sign_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
