# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.runs/synth_1/.Xil/Vivado-8224-LAPTOP-6MP61O86/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7k70tfbv676-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/ALU.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/BranchControl.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/CP0.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/Ctrl.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/DMEM.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/Decoder.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/EX_ME.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/ID_EX.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/IF_ID.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/IMEM.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/ME_WB.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/MUX1.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/MUX2.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/MUX3.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/PC.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/RG.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/WHUCPU.v
      D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.srcs/sources_1/new/WHUCPU_soc.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top WHUCPU_soc
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.cache/wt}
    rt::set_parameter enableSplitFlowPath "D:/225/2020计组MIPS/addr/WHUMIPS/whu_cpu.runs/synth_1/.Xil/Vivado-8224-LAPTOP-6MP61O86/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
